import type { Metadata } from "next";
import { Bruno_Ace } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Header from "@/components/Header";

const inter = Bruno_Ace({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="snap-y snap-mandatory scroll-smooth ">
      <body
        className={`${inter.className} container selection:bg-primary-200/90 max-w-7xl`}
      >
        <NavBar />
        <Header />
        {children}
      </body>
    </html>
  );
}
